### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by DadiBit** [italia/cie-middleware-linux#84]
Vorrei proporre l'implementazione del codice sorgente in un "comodo" flatpak, tornerebbe molto utile per l'installazione da parte di utenti meno esperti.

In pratica si mette tutto (librerie e app) all'interno di una "scatola" che accede esclusivamente a certe parti del sistema (network e all-devices per il lettore).

**Comment by DadiBit** [comment]
**NB: non avendo al momento un lettore CIE disponibile mi trovo a non poter testare l'effettivo utilizzo del software.**

## Requisiti

Installare [flatpak builder](https://github.com/flatpak/flatpak-builder/) con uno dei seguenti metodi:
1. Compilarlo e installarlo dalla sorgente
2. Installare il pachetto `flatpak-builder` tramite il proprio package manager (dnf/apt/pacman)
3. Installare il flatpak `org.flatpak.Builder` con `flatpak install org.flatpak.Builder`
   - Possiamo assegnare un alias `alias flatpak-builder="flatpak run org.flatpak.Builder"` per comodità
4. In alternative è possibile lavorare con `flatpak build`, ma risulta più elaborato come processo.

Aggiungiamo la repo sorgente `flathub` a livello di utente con:
```
flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
```

## Build

> [Documentazione flatpak](https://docs.flatpak.org/en/latest/first-build.html)

Creiamo una cartella dove lavorare, e.g.: `it.ipzs.cieid`, ed entriamo al suo interno.

Creiamo il file manifest `it.ipzs.cieid.yml`:
```yaml
id: it.ipzs.cieid
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk
command: cieid-launcher # You cannot run `java` with arguments, we need a launcher script!
rename-icon: cieid
rename-desktop-file: cieid.desktop
modules:
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk/install.sh
  - name: PCSC-lite-Middleware
    buildsystem: meson
    config-opts:
      - -Dpolkit=false
      - -Dlibsystemd=false
    sources:
      - type: archive
        url: https://pcsclite.apdu.fr/files/pcsc-lite-2.3.0.tar.xz
        sha256: 1acca22d2891d43ffe6d782740d32e78150d4fcc99e8a3cc763abaf546060d3d
  - name: CIE-Middleware
    buildsystem: simple
    build-commands:
      - mkdir -p /app/bin /app/lib /app/share/CIEID/lib /app/share/applications /app/share/CIEID /app/share/icons/hicolor/256x256/apps/ /app/usr/lib
      # Copy the library to standard paths
      - cp -r usr/local/lib/libcie-pkcs11.so /app/lib/
      # Copy the desktop file and fix paths
      - cp usr/share/applications/cieid.desktop /app/share/applications/
      - sed -i 's|^Exec=.*|Exec=cieid-launcher|' /app/share/applications/cieid.desktop
      - sed -i 's|^Icon=.*|Icon=cieid|' /app/share/applications/cieid.desktop
      # Copy the JAR file and the icon
      - cp -r usr/share/CIEID/cieid.jar /app/share/CIEID/cieid.jar
      - cp -r usr/share/CIEID/logo_circle.png /app/share/icons/hicolor/256x256/apps/cieid.png
      # Create the wrapper script
      - echo '#!/bin/sh' > /app/bin/cieid-launcher
      - echo 'exec java -Xms1G -Xmx1G -Djna.debug_load=true -Djna.debug_load.jna=true -classpath "/app/share/CIEID/cieid.jar" it.ipzs.cieid.MainApplication "$@"' >> /app/bin/cieid-launcher
      - chmod +x /app/bin/cieid-launcher
    sources:
      - type: archive
        url: https://github.com/italia/cie-middleware-linux/releases/download/1.4.3.10/CIE-Middleware-1.4.3-10.x86-64.tar.gz
        sha256: 4ecb3929a9b731b871406fcdbab3eb3cf32087daa50900be17b7e1a6fd2a2eac
finish-args:
  - "--env=PATH=/app/jre/bin:/app/bin:/usr/bin"
  - "--env=JAVA_HOME=/app/jre"
  - "--env=CLASSPATH=/app/share/CIEID/cieid.jar"
  - --device=dri
  - --device=all
  - --socket=x11
  - --socket=pcsc # If removed gets program stuck on waiting reader
  - --share=network # Required to access information, documentation etc.
  - --filesystem=home:rw # ~/.CIEID and ~/.CIEPKI access
```

Compiliamo il programma con:
```
flatpak run org.flatpak.Builder --force-clean --user --install-deps-from=flathub --repo=repo --install build it.ipzs.cieid.yml
```
NB: tutti i requisiti/sdk vengono scaricati/aggiornati in automatico durante la build.

Done! Puoi avviare l'app con:
```
flatpak run --user it.ipzs.cieid
```
Oppure semplicemente dal menu delle app del proprio sistema operativo

Per disinstallare l'app basta fare: `flatpak remove --user it.ipzs.cieid`

Bug riscontrati:
1. Senza il socket pcsc il programma resta in attesa del lettore

PS: è la prima volta che compilo un flatpak: ci sono sicuramente dei punti su cui migliorare il file Manifest prima di una possibile pubblicazione (autore, versione ecc), tuttavia da quanto riesco a testare io l'app parte.
